// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import { PlasmicEffectItem, DefaultEffectItemProps } from './plasmic/synthetic_prop_creator/PlasmicEffectItem';
import { HTMLElementRefOf, set } from '@plasmicapp/react-web';

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface EffectItemProps extends Omit<DefaultEffectItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultEffectItemProps altogether and have
// total control over the props for your component.
export interface EffectItemProps extends DefaultEffectItemProps {}

function EffectItem_(props: EffectItemProps, ref: HTMLElementRefOf<'div'>) {
  


  return <PlasmicEffectItem  root={{ ref }} {...props} />;
}

const EffectItem = React.forwardRef(EffectItem_);
export default EffectItem;
