// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import { PlasmicOptionItem, DefaultOptionItemProps } from './plasmic/synthetic_prop_creator/PlasmicOptionItem';
import { HTMLElementRefOf } from '@plasmicapp/react-web';

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface OptionItemProps extends Omit<DefaultOptionItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultOptionItemProps altogether and have
// total control over the props for your component.
export interface OptionItemProps extends DefaultOptionItemProps {}

function OptionItem_(props: OptionItemProps, ref: HTMLElementRefOf<'div'>) {
  // Use PlasmicOptionItem to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicOptionItem are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all OptionItemProps here, but feel free
  // to do whatever works for you.

  return <PlasmicOptionItem root={{ ref }} {...props} />;
}

const OptionItem = React.forwardRef(OptionItem_);
export default OptionItem;
