// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kh4DHzfPKxHW3t3zk2aoXn
// Component: 0gQ3RbV4NzdZ9M

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import IconButton from '../../IconButton'; // plasmic-import: 0Jteo_49Jd/component

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_synthetic_prop_creator.module.css'; // plasmic-import: kh4DHzfPKxHW3t3zk2aoXn/projectcss
import sty from './PlasmicGroup.module.css'; // plasmic-import: 0gQ3RbV4NzdZ9M/css

export type PlasmicGroup__VariantMembers = {
  open: 'open';
  hidden: 'hidden';
};

export type PlasmicGroup__VariantsArgs = {
  open?: SingleBooleanChoiceArg<'open'>;
  hidden?: SingleBooleanChoiceArg<'hidden'>;
};

type VariantPropType = keyof PlasmicGroup__VariantsArgs;
export const PlasmicGroup__VariantProps = new Array<VariantPropType>('open', 'hidden');

export type PlasmicGroup__ArgsType = {
  children?: React.ReactNode;
  groupName?: string;
  onGroupNameChange?: (val: string) => void;
};

type ArgPropType = keyof PlasmicGroup__ArgsType;
export const PlasmicGroup__ArgProps = new Array<ArgPropType>('children', 'groupName', 'onGroupNameChange');

export type PlasmicGroup__OverridesType = {
  root?: p.Flex<'div'>;
  text?: p.Flex<'div'>;
  plus?: p.Flex<typeof IconButton>;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultGroupProps {
  children?: React.ReactNode;
  groupName?: string;
  onGroupNameChange?: (val: string) => void;
  open?: SingleBooleanChoiceArg<'open'>;
  hidden?: SingleBooleanChoiceArg<'hidden'>;
  className?: string;
}

const __wrapUserFunction = globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicGroup__RenderFunc(props: {
  variants: PlasmicGroup__VariantsArgs;
  args: PlasmicGroup__ArgsType;
  overrides: PlasmicGroup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: 'groupName',
        type: 'writable',
        variableType: 'text',

        valueProp: 'groupName',
        onChangeProp: 'onGroupNameChange',
      },
      {
        path: 'open',
        type: 'private',
        variableType: 'variant',
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.open,
      },

      {
        path: 'hidden',
        type: 'private',
        variableType: 'variant',
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.hidden,
      },
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    (hasVariant($state, 'hidden', 'hidden') ? false : true) ? (
      <div
        data-plasmic-name={'root'}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root,
          {
            [sty.roothidden]: hasVariant($state, 'hidden', 'hidden'),
            [sty.rootopen]: hasVariant($state, 'open', 'open'),
          }
        )}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox___1G5Nw, {
            [sty.freeBoxopen___1G5NwTlE1O]: hasVariant($state, 'open', 'open'),
          })}
        >
          <div
            data-plasmic-name={'text'}
            data-plasmic-override={overrides.text}
            className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
              [sty.textopen]: hasVariant($state, 'open', 'open'),
            })}
          >
            {(() => {
              try {
                return $state.groupName;
              } catch (e) {
                if (e instanceof TypeError) {
                  return 'Group name';
                }
                throw e;
              }
            })()}
          </div>
          <IconButton
            data-plasmic-name={'plus'}
            data-plasmic-override={overrides.plus}
            className={classNames('__wab_instance', sty.plus, { [sty.plusopen]: hasVariant($state, 'open', 'open') })}
          >
            <p.PlasmicImg
              data-plasmic-name={'img'}
              data-plasmic-override={overrides.img}
              alt={''}
              className={classNames(sty.img, { [sty.imgopen]: hasVariant($state, 'open', 'open') })}
              displayHeight={'12px' as const}
              displayMaxHeight={'none' as const}
              displayMaxWidth={'100%' as const}
              displayMinHeight={'0' as const}
              displayMinWidth={'0' as const}
              displayWidth={'12px' as const}
              loading={'lazy' as const}
              src={{
                src: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMyAxMiI+CiAgPGcgY2xpcC1wYXRoPSJ1cmwoI3dtN29OOEU5QmEpIj4KICAgIDxwYXRoIGQ9Ik01Ljc1IDUuNXYtNWgxdjVoNXYxaC01djVoLTF2LTVoLTV2LTFoNXoiIGZpbGw9IiMwMDAiLz4KICA8L2c+CiAgPGRlZnM+CiAgICA8Y2xpcFBhdGggaWQ9IndtN29OOEU5QmEiPgogICAgICA8cGF0aCBmaWxsPSIjZmZmIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSguMjUpIiBkPSJNMCAwaDEydjEySDB6Ii8+CiAgICA8L2NsaXBQYXRoPgogIDwvZGVmcz4KPC9zdmc+Cg==',
                fullWidth: 163,
                fullHeight: 150,
                aspectRatio: 1.083333,
              }}
            />
          </IconButton>
        </div>
        {true ? (
          <p.Stack
            as={'div'}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__intwY, {
              [sty.freeBoxopen__intwYTlE1O]: hasVariant($state, 'open', 'open'),
            })}
          >
            {(hasVariant($state, 'open', 'open') ? true : true)
              ? p.renderPlasmicSlot({
                  defaultContents: null,
                  value: args.children,
                })
              : null}
          </p.Stack>
        ) : null}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'text', 'plus', 'img'],
  text: ['text'],
  plus: ['plus', 'img'],
  img: ['img'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: 'div';
  text: 'div';
  plus: typeof IconButton;
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicGroup__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicGroup__VariantsArgs;
  args?: PlasmicGroup__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicGroup__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicGroup__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGroup__ArgProps,
          internalVariantPropNames: PlasmicGroup__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicGroup__RenderFunc({ variants, args, overrides, forNode: nodeName });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicGroup';
  } else {
    func.displayName = `PlasmicGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicGroup = Object.assign(
  // Top-level PlasmicGroup renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent('text'),
    plus: makeNodeComponent('plus'),
    img: makeNodeComponent('img'),

    // Metadata about props expected for PlasmicGroup
    internalVariantProps: PlasmicGroup__VariantProps,
    internalArgProps: PlasmicGroup__ArgProps,
  }
);

export default PlasmicGroup;
/* prettier-ignore-end */
