// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kh4DHzfPKxHW3t3zk2aoXn
// Component: f-2yG4nl9J

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_synthetic_prop_creator.module.css'; // plasmic-import: kh4DHzfPKxHW3t3zk2aoXn/projectcss
import sty from './PlasmicSettingButton.module.css'; // plasmic-import: f-2yG4nl9J/css

import Icon6Icon from './icons/PlasmicIcon__Icon6'; // plasmic-import: 6mZ-ajJ6aX/icon

export type PlasmicSettingButton__VariantMembers = {};

export type PlasmicSettingButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicSettingButton__VariantsArgs;
export const PlasmicSettingButton__VariantProps = new Array<VariantPropType>();

export type PlasmicSettingButton__ArgsType = {};
type ArgPropType = keyof PlasmicSettingButton__ArgsType;
export const PlasmicSettingButton__ArgProps = new Array<ArgPropType>();

export type PlasmicSettingButton__OverridesType = {
  root?: p.Flex<'div'>;
  svg?: p.Flex<'svg'>;
};

export interface DefaultSettingButtonProps {
  className?: string;
}

const __wrapUserFunction = globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSettingButton__RenderFunc(props: {
  variants: PlasmicSettingButton__VariantsArgs;
  args: PlasmicSettingButton__ArgsType;
  overrides: PlasmicSettingButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const [isRootHover, triggerRootHoverProps] = useTrigger('useHover', {});
  const triggers = {
    hover_root: isRootHover,
  };

  return (
    (triggers.hover_root ? true : true) ? (
      <div
        data-plasmic-name={'root'}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
        data-plasmic-trigger-props={[triggerRootHoverProps]}
      >
        <Icon6Icon
          data-plasmic-name={'svg'}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={'img'}
        />
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'svg'],
  svg: ['svg'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: 'div';
  svg: 'svg';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicSettingButton__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicSettingButton__VariantsArgs;
  args?: PlasmicSettingButton__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicSettingButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicSettingButton__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSettingButton__ArgProps,
          internalVariantPropNames: PlasmicSettingButton__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicSettingButton__RenderFunc({ variants, args, overrides, forNode: nodeName });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicSettingButton';
  } else {
    func.displayName = `PlasmicSettingButton.${nodeName}`;
  }
  return func;
}

export const PlasmicSettingButton = Object.assign(
  // Top-level PlasmicSettingButton renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent('svg'),

    // Metadata about props expected for PlasmicSettingButton
    internalVariantProps: PlasmicSettingButton__VariantProps,
    internalArgProps: PlasmicSettingButton__ArgProps,
  }
);

export default PlasmicSettingButton;
/* prettier-ignore-end */
